[project]
name = "python-cursor-dashboard"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "dash==2.14.2",
    "gunicorn==21.2.0",
    "numpy==1.24.3",
    "pandas==2.0.3",
    "plotly==5.17.0",
]
